### ISSUE TITLE
Providing official binaries for ARMv8  

### ISSUE THREAD

**Issue by khasim** [nuxeo/docker-nuxeo#21] opened 2018-07-31 14:34 UTC
Hi,

As I didn't find any forum to discuss this topic, I have raised this request as an issue. 

As we can successfully build and run Nuxeo for ARMv8 docker containers, I would like to know if there were any plans in releasing official ARMv8 binaries of Nuxeo on docker hub.

Thanks.

Regards,
Khasim

**Comment by dmetzler** [comment] 2018-07-31 15:16
No plan for now. 
Nuxeo only needs a JVM, any precise need on your side?

**Comment by khasim** [comment] 2018-08-02 08:45
I was trying to enable few docker projects on hub.docker for ARMv8 and as I found Nuxeo already working for ARMv8, I was interested to know if we could get an official binary and make it readily available for interested developers.

Thanks.

**Comment by dmetzler** [comment] 2018-08-06 08:54
Unless we have some real customers interested in it, we won't provide such support.

**Comment by odidev** [comment] 2018-08-09 10:26
Hi @khasim - I am very curious to know about this...
Have you done any change to run ```nuxeo``` on ```arm64v8``` architecture?

I am also working on Nuxeo for ARM64, but I am facing a JVM crash at runtime.

**Comment by khasim** [comment] 2018-08-09 13:05
Hi @odidev did you try with dockerfile in 10.2. Also, I only tried running non-production setup,

docker run --name mynuxeo -p 8080:8080 -d nuxeo

**Comment by odidev** [comment] 2018-08-09 13:12
@khasim- Yes, I did try ```10.2```.
But still I can see JVM crash.

Are you able to open webpage after running your docker image?
Also can you check running your image without ```-d``` option.

```docker run --name mynuxeo -p 8080:8080 nuxeo ```

**Comment by khasim** [comment] 2018-08-09 14:45
@odidev , yes without -d I do see JVM crash.

**Comment by odidev** [comment] 2018-08-09 15:01
@khasim - So this means we are on same page now.
```-d``` option detaches the container and then you will not be able to see what is going on inside.

In addition, what about the webpage? Does it open for you?

And how did you validate whether ```nuxeo``` is working properly or not?
Did you run some test cases for confirmation?

Now my concern is regarding the observed JVM crash.
It would be great if you spend some time in observed crash. 
Probably support for ```arm64v8``` can be added once we have concrete proven run-time data.

**Comment by dmetzler** [comment] 2018-08-09 15:30
For the record, I've at least been able to run Nuxeo on a RaspberryPi3 two years ago, but not in Docker:

![img_1384](https://user-images.githubusercontent.com/111077/43908969-937e3232-9bf9-11e8-8536-ee21c13963ff.JPG)

**Comment by odidev** [comment] 2018-08-09 15:33
@dmetzler - Can you please give it a try over Docker too?

**Comment by dmetzler** [comment] 2018-08-09 15:44
If I find time and I find back that Raspberry :)
To be honest it was very very slow, and practically unusable.

**Comment by khasim** [comment] 2018-08-09 18:49
The JVM crash is SIGBUS (0x7) which is mainly due to insufficient tmp space (AFAIK). But when I attach to the container running nuxeo, I don't see insufficient memory being the real cause. There is enough memory available and tmp is almost empty.

ls -l /opt/nuxeo/server/tmp
total 15136
-rw-r--r-- 1 nuxeo nuxeo 15493545 Aug  9 17:42 nuxeo-launcher-2683.jar
drwxr-xr-x 2 nuxeo nuxeo     4096 Aug  9 17:42 schem

Not sure if this folder should be empty. Will find some time tomorrow to analyze further.

**Comment by khasim** [comment] 2018-08-13 10:48
Here are my findings so far 

- When I attach to container shell and start nuxeo  - its successful, I can even browse the page and I don't see any JVM crashes.

- nuxeoctl start
Detected Tomcat server.
Nuxeo home:          /opt/nuxeo/server
Nuxeo configuration: /etc/nuxeo/nuxeo.conf
Include template: /opt/nuxeo/server/templates/common-base
Include template: /opt/nuxeo/server/templates/common
Include template: /opt/nuxeo/server/templates/default
Include template: /opt/nuxeo/server/templates/docker
Configuration files generation (nuxeo.force.generation=true)...
Configuration files generated.
Server started with process ID 2213.
..........................
======================================================================
Component Loading Status: Pending: 0 / Missing: 0 / Unstarted: 1 / Total: 489
service:org.nuxeo.runtime.stream.service
======================================================================
Started in 0min52s
Go to http://localhost:8080/nuxeo

- nuxeoctl console 
When I run the CMD that docker file is executing from the container shell ($ nuxeoctl console) I see java exceptions. I think this is related to logging..

2018-08-13 09:53:48,904 ERROR [RegistrationInfoImpl] Component service:org.nuxeo.runtime.stream.service notification of application started failed: Cannot add -89 bytes of padding
java.lang.IllegalStateException: Cannot add -89 bytes of padding
	at net.openhft.chronicle.wire.BinaryWire.addPadding(BinaryWire.java:1066)

The platform does start at the end 

- 2018-08-13 09:54:21,789 ERROR [OSGiRuntimeService] Nuxeo Platform Started
======================================================================
Component Loading Status: Pending: 0 / Missing: 0 / Unstarted: 1 / Total: 489
service:org.nuxeo.runtime.stream.service
======================================================================
2018-08-13 09:54:23.919 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 52506 ms

**Comment by odidev** [comment] 2018-08-14 08:48
I agree that ```Nuxeo``` is working fine when used with
**```nuxeoctl start```**

Now we need to see whether this can be accepted or not.
If yes, then we need to modify ```Dockerfile```.

@dmetzler - What do you say?

**Comment by dmetzler** [comment] 2018-08-14 09:30
Did you try to add a `-ti` flag to you Docker command in order to attach the terminal? The thing is that `nuxeoctl console` just attach the log to the console which is the standard way of doing it with Docker.

The error with ChronicleQueue should be reviewed. As CQ is an off-heap queuing mechanism, it can be platform dependent and not work on this infrastructure. It's an important part of Nuxeo (everything that is asynchronous), so if it doesn't work, that's a big problem.

If it's only for the fun, I don't think it's worth it to dig further unless you have a real use case.

**Comment by odidev** [comment] 2018-08-14 10:36
Hi @dmetzler ,
Can we reopen this ticket?

I think ```arm64v8``` can be supported for ```nuxeo```.

**Comment by dmetzler** [comment] 2018-08-14 12:04
@odidev The question raised by this ticket is whether or not there are plans for supporting `arm64v8`. 

Supporting doesn't only mean succeeding in making Nuxeo start but also making the full test suite pass, and maintaining it. As we don't have any real use case or customer expecting that support for now (and wanting to pay for it), we won't support it.

So the answer to this ticket is clear to me, that's why I closed it.

**Comment by odidev** [comment] 2018-08-14 12:15
@dmetzler 
Hi Damien,
I do agree with your concern.

Regarding demand for ARM64, I would say that most of the Docker modules have started to work in the direction of ARM64 as it is getting popular in the market.

I appreciate your position and what you said above makes sense. The only thing that I would add would be to comment for people possibly experimenting with ```nuxeo``` on Raspberry PIs or even larger systems like ThunderX (96 cores via packet.net which are cheap and efficient) - I would hope that people will be able to build this themselves without too much extra trouble but here's additional information:
```
Shippable supports free Arm64 CI/CD and I believe Codefresh does too (both 64-bit and 32-bit for both providers):

https://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture
http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/

CodeFresh Beta signup: https://goo.gl/forms/aDhlk56jZcblYokj1

If you need raw infrastructure the WorksOnArm project will supply full servers if you want to deal with metal: https://github.com/worksonarm/cluster/
```
Would really love to see nuxeo on ARM!  :smile: 

In case you plan to change your mind and plan to support ```arm64v8```, do let me know.
Thank you again and I hope we can help generate demand for Nuxeo on Arm.

@mmarmm: Any comments, buddy?

Regards,

**Comment by dmetzler** [comment] 2018-08-14 12:55
FYI I've created a ticket in our internal innovation JIRA (not public though). So, no promise here.

**Comment by efge** [comment] 2018-08-17 15:56
@khasim do you have more lines of the stack trace that starts with the following?

    2018-08-13 09:53:48,904 ERROR [RegistrationInfoImpl] Component service:org.nuxeo.runtime.stream.service notification of application started failed: Cannot add -89 bytes of padding
    java.lang.IllegalStateException: Cannot add -89 bytes of padding
    at net.openhft.chronicle.wire.BinaryWire.addPadding(BinaryWire.java:1066)

**Comment by khasim** [comment] 2018-08-18 02:57
Does this help ?

======================================================================
  * Server home = /opt/nuxeo/server
  * Runtime home = /opt/nuxeo/server/nxserver
  * Data Directory = /var/lib/nuxeo/data
  * Log Directory = /var/log/nuxeo
  * Configuration Directory = /opt/nuxeo/server/nxserver/config
  * Temp Directory = /opt/nuxeo/server/tmp
======================================================================
2018-08-13 09:53:48,904 ERROR [RegistrationInfoImpl] Component service:org.nuxeo.runtime.stream.service notification of application started failed: Cannot add -89 bytes of padding
java.lang.IllegalStateException: Cannot add -89 bytes of padding
	at net.openhft.chronicle.wire.BinaryWire.addPadding(BinaryWire.java:1066)
	at net.openhft.chronicle.queue.impl.single.TimedStoreRecovery.recoverAndWriteHeader(TimedStoreRecovery.java:101)
	at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.build(SingleTableBuilder.java:128)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.<init>(SingleChronicleQueue.java:157)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:194)
	at org.nuxeo.lib.stream.log.chronicle.ChronicleLogAppender.initPartitions(ChronicleLogAppender.java:126)
	at org.nuxeo.lib.stream.log.chronicle.ChronicleLogAppender.<init>(ChronicleLogAppender.java:113)
	at org.nuxeo.lib.stream.log.chronicle.ChronicleLogAppender.open(ChronicleLogAppender.java:171)
	at org.nuxeo.lib.stream.log.chronicle.ChronicleLogManager.createAppender(ChronicleLogManager.java:199)
	at org.nuxeo.lib.stream.log.internals.AbstractLogManager.lambda$getAppender$3(AbstractLogManager.java:150)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.nuxeo.lib.stream.log.internals.AbstractLogManager.getAppender(AbstractLogManager.java:148)
	at org.nuxeo.lib.stream.computation.log.LogStreamProcessor.lambda$initSourceAppenders$12(LogStreamProcessor.java:230)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.nuxeo.lib.stream.computation.log.LogStreamProcessor.initSourceAppenders(LogStreamProcessor.java:229)
	at org.nuxeo.lib.stream.computation.log.LogStreamProcessor.init(LogStreamProcessor.java:73)
	at org.nuxeo.runtime.stream.StreamServiceImpl.initProcessor(StreamServiceImpl.java:158)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at org.nuxeo.runtime.stream.StreamServiceImpl.start(StreamServiceImpl.java:141)
	at org.nuxeo.runtime.model.impl.RegistrationInfoImpl.start(RegistrationInfoImpl.java:382)
	at org.nuxeo.runtime.model.impl.ComponentManagerImpl.startComponent(ComponentManagerImpl.java:709)
	at org.nuxeo.runtime.model.impl.ComponentManagerImpl.startComponents(ComponentManagerImpl.java:689)
	at org.nuxeo.runtime.model.impl.ComponentManagerImpl.start(ComponentManagerImpl.java:792)
	at org.nuxeo.runtime.osgi.OSGiRuntimeService.startComponents(OSGiRuntimeService.java:460)
	at org.nuxeo.runtime.osgi.OSGiRuntimeService.frameworkEvent(OSGiRuntimeService.java:475)
	at org.nuxeo.osgi.OSGiAdapter.fireFrameworkEvent(OSGiAdapter.java:223)
	at org.nuxeo.osgi.application.loader.FrameworkLoader.doStart(FrameworkLoader.java:225)
	at org.nuxeo.osgi.application.loader.FrameworkLoader.start(FrameworkLoader.java:124)
	at org.nuxeo.runtime.deployment.NuxeoStarter.start(NuxeoStarter.java:124)
	at org.nuxeo.runtime.deployment.NuxeoStarter.contextInitialized(NuxeoStarter.java:93)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:630)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1842)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-13 09:53:52,544 WARN  [ElasticSearchEmbeddedNode] Elasticsearch embedded configuration is ONLY for testing purpose. You need to create a dedicated Elasticsearch cluster for production.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
2018-08-13 09:54:21,731 WARN  [Transaction] Unexpected exception from afterCompletion; continuing
java.lang.IllegalStateException: Cannot add -89 bytes of padding
	at net.openhft.chronicle.wire.BinaryWire.addPadding(BinaryWire.java:1066)
	at net.openhft.chronicle.queue.impl.single.TimedStoreRecovery.recoverAndWriteHeader(TimedStoreRecovery.java:101)
	at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.build(SingleTableBuilder.java:128)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.<init>(SingleChronicleQueue.java:157)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:194)
	at org.nuxeo.lib.stream.log.chronicle.ChronicleLogAppender.initPartitions(ChronicleLogAppender.java:126)
	at org.nuxeo.lib.stream.log.chronicle.ChronicleLogAppender.<init>(ChronicleLogAppender.java:113)
	at org.nuxeo.lib.stream.log.chronicle.ChronicleLogAppender.open(ChronicleLogAppender.java:171)
	at org.nuxeo.lib.stream.log.chronicle.ChronicleLogManager.createAppender(ChronicleLogManager.java:199)
	at org.nuxeo.lib.stream.log.internals.AbstractLogManager.lambda$getAppender$3(AbstractLogManager.java:150)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.nuxeo.lib.stream.log.internals.AbstractLogManager.getAppender(AbstractLogManager.java:148)
	at org.nuxeo.lib.stream.log.LogManager.getAppender(LogManager.java:79)
	at org.nuxeo.ecm.platform.audit.listener.StreamAuditEventListener.writeEntries(StreamAuditEventListener.java:122)
	at org.nuxeo.ecm.platform.audit.listener.StreamAuditEventListener.afterCompletion(StreamAuditEventListener.java:108)
	at org.apache.geronimo.transaction.manager.TransactionImpl.afterCompletion(TransactionImpl.java:540)
	at org.apache.geronimo.transaction.manager.TransactionImpl.afterCompletion(TransactionImpl.java:533)
	at org.apache.geronimo.transaction.manager.TransactionImpl.commit(TransactionImpl.java:329)
	at org.apache.geronimo.transaction.manager.TransactionManagerImpl.commit(TransactionManagerImpl.java:252)
	at org.nuxeo.runtime.jtajca.NuxeoContainer$UserTransactionImpl.commit(NuxeoContainer.java:538)
	at org.nuxeo.runtime.transaction.TransactionHelper.commitOrRollbackTransaction(TransactionHelper.java:363)
	at org.nuxeo.runtime.transaction.TransactionHelper.runInTransaction(TransactionHelper.java:599)
	at org.nuxeo.runtime.transaction.TransactionHelper.runInTransaction(TransactionHelper.java:569)
	at org.nuxeo.ecm.core.repository.RepositoryService.initRepositories(RepositoryService.java:91)
	at org.nuxeo.ecm.core.repository.RepositoryService$1.afterStart(RepositoryService.java:69)
	at org.nuxeo.runtime.model.impl.ComponentManagerImpl$Listeners.afterStart(ComponentManagerImpl.java:1136)
	at org.nuxeo.runtime.model.impl.ComponentManagerImpl.startComponents(ComponentManagerImpl.java:693)
	at org.nuxeo.runtime.model.impl.ComponentManagerImpl.start(ComponentManagerImpl.java:792)
	at org.nuxeo.runtime.osgi.OSGiRuntimeService.startComponents(OSGiRuntimeService.java:460)
	at org.nuxeo.runtime.osgi.OSGiRuntimeService.frameworkEvent(OSGiRuntimeService.java:475)
	at org.nuxeo.osgi.OSGiAdapter.fireFrameworkEvent(OSGiAdapter.java:223)
	at org.nuxeo.osgi.application.loader.FrameworkLoader.doStart(FrameworkLoader.java:225)
	at org.nuxeo.osgi.application.loader.FrameworkLoader.start(FrameworkLoader.java:124)
	at org.nuxeo.runtime.deployment.NuxeoStarter.start(NuxeoStarter.java:124)
	at org.nuxeo.runtime.deployment.NuxeoStarter.contextInitialized(NuxeoStarter.java:93)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:630)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1842)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-13 09:54:21,789 ERROR [OSGiRuntimeService] Nuxeo Platform Started
======================================================================
= Component Loading Status: Pending: 0 / Missing: 0 / Unstarted: 1 / Total: 489
  - service:org.nuxeo.runtime.stream.service
======================================================================
2018-08-13 09:54:23.919 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 52506 ms

**Comment by efge** [comment] 2018-08-20 11:23
@khasim thanks

**Comment by efge** [comment] 2018-08-25 15:57
FYI I've opened this with Chronicle for the JVM crash: https://github.com/OpenHFT/Chronicle-Queue/issues/528

**Comment by lag-linaro** [comment] 2018-10-17 09:28
I see that Chronicle-Queue-5.16.15 was released around 3 weeks ago, but I still experience a SIGBUS issue when running on AArch64:

```$ docker run -ti --rm --name mynuxeo -p 8080:8080 7fcec80da922
/docker-entrypoint.sh: ignoring /docker-entrypoint-initnuxeo.d/*
Detected Tomcat server.
Nuxeo home:          /opt/nuxeo/server
Nuxeo configuration: /etc/nuxeo/nuxeo.conf
Include template: /opt/nuxeo/server/templates/common-base
Include template: /opt/nuxeo/server/templates/common
Include template: /opt/nuxeo/server/templates/default
Include template: /opt/nuxeo/server/templates/docker
No current configuration, generating files...
Configuration files generated.
Server started with process ID 258.
Go to http://localhost:8080/nuxeo
2018-10-16 11:12:11.601 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1111 ms
# Running Nuxeo Preprocessor ...
Preprocessing: /opt/nuxeo/server/nxserver
Done.
# Preprocessing done.
2018-10-16 11:12:15,848 INFO  [FrameworkLoader] 
======================================================================
= Starting Nuxeo Framework
======================================================================
  * Server home = /opt/nuxeo/server
  * Runtime home = /opt/nuxeo/server/nxserver
  * Data Directory = /var/lib/nuxeo/data
  * Log Directory = /var/log/nuxeo
  * Configuration Directory = /opt/nuxeo/server/nxserver/config
  * Temp Directory = /opt/nuxeo/server/tmp
======================================================================
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x0000ffff9d6f21e0, pid=258, tid=0x0000fffeefdff200
#
# JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-8u171-b11-1~deb9u1-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-aarch64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x9631e0]
#
# Core dump written. Default location: /opt/nuxeo/server/core or core.258
#
# An error report file with more information is saved as:
# /opt/nuxeo/server/hs_err_pid258.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

Is this the same issue, or a different one?

**Comment by efge** [comment] 2018-10-19 12:19
5.16.15 was still buggy due to misdetection of aarch64, but I was in contact with the Chronicle guys and they finally found a fix and I tested it successfully. I don't know if it's already released and in what Chronicle version though (we don't actually use Nuxeo on ARM64 here).

**Comment by odidev** [comment] 2018-10-31 05:22
Hi @efge 
Can you please check whether the fixed version of Chronicle has been released or not.
If yes, then when can we have an official package from Nuxeo community with the fixed version, as Dockerfile will be fetching Nuxeo package from community page.

Regards,

**Comment by efge** [comment] 2018-10-31 17:24
The fixed version has been released. We'll upgrade soon.

**Comment by bdelbosc** [comment] 2018-11-08 09:14
FYI, upgrade of Chronicle Queue has been done (bom version 2.17.28)
and Nuxeo is great again on Raspberry Pi !
```
$ uname -a
Linux raspberrypi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux
$ ./bin/nuxeoctl start
...
======================================================================
= Component Loading Status: Pending: 0 / Missing: 0 / Unstarted: 0 / Total: 677
======================================================================
Started in 2min38s
```
more info in https://jira.nuxeo.com/browse/NXP-26121
Regards.

**Comment by lag-linaro** [comment] 2018-11-08 09:58
That's great news.

Do we know when 10.3 will be released, so we can use it?

**Comment by odidev** [comment] 2018-11-08 15:58
Although, I have observed that there are updates in ```Snapshots``` version at Nuxeo community, but it would require an official update at ```release``` section for using in Dockerfile.

**Comment by bdelbosc** [comment] 2018-11-09 09:07
Hi, yes for testing you can use a [snapshot](http://community.nuxeo.com/static/snapshots/nuxeo-server-tomcat-10.3-SNAPSHOT.zip), Nuxeo 10.3 fast track is scheduled for the beginning of December.

**Comment by odidev** [comment] 2018-11-14 05:21
Hi @bdelbosc 
Yes, Nuxeo is working without any crash with the ```snapshot``` package shared by you.

Now, let's wait for the official release of Nuxeo, which can be used at docker end too.

Regards,

**Comment by lag-linaro** [comment] 2018-12-04 10:15
Good morning @bdelbosc.  How's that 'beginning of December' deadline looking? :smiley:

**Comment by odidev** [comment] 2018-12-14 07:28
Well, I see ```Nuxeo: 10.3``` has been pushed, It seems we should get some good news regarding AARCH64 too

**Comment by odidev** [comment] 2018-12-14 08:17
Hi @bdelbosc @dmetzler 

I have confirmed working of ```Nuxeo-10.3``` over ARM64 architecture and the things are working fine without any modification.
This makes me say that Nuxeo does support ```arm64v8``` now.

Can you update your already going PR https://github.com/docker-library/official-images/pull/5179 with the update regarding ```Architectures``` or should a separate PR be required for it?

Regards,

**Comment by lag-linaro** [comment] 2018-12-14 08:51
I too have tested this on `aarch64` seems to work well:

```
user@host:~$ uname -a
Linux devbox 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:22:18 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

user@host:~/projects/docker-hub/docker-nuxeo [master]$ docker run -ti --rm afb6e4ec1604
/docker-entrypoint.sh: ignoring /docker-entrypoint-initnuxeo.d/*
Detected Tomcat server.
Nuxeo home:          /opt/nuxeo/server
Nuxeo configuration: /etc/nuxeo/nuxeo.conf
Include template: /opt/nuxeo/server/templates/common-base
Include template: /opt/nuxeo/server/templates/common
Include template: /opt/nuxeo/server/templates/default
Include template: /opt/nuxeo/server/templates/docker
No current configuration, generating files...
Configuration files generated.
Server started with process ID 165.
Go to http://localhost:8080/nuxeo
2018-12-14 08:46:02.427 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 3098 ms
# Running Nuxeo Preprocessor ...
Preprocessing: /opt/nuxeo/server/nxserver
Done.
# Preprocessing done.
2018-12-14T08:46:14,363 INFO  [FrameworkLoader]
======================================================================
= Starting Nuxeo Framework
======================================================================
  * Server home = /opt/nuxeo/server
  * Runtime home = /opt/nuxeo/server/nxserver
  * Data Directory = /var/lib/nuxeo/data
  * Log Directory = /var/log/nuxeo
  * Configuration Directory = /opt/nuxeo/server/nxserver/config
  * Temp Directory = /opt/nuxeo/server/tmp
======================================================================
2018-12-14T08:46:59,854 WARN  [ElasticSearchEmbeddedNode] Elasticsearch embedded configuration is ONLY for testing purpose. You need to create a dedicated Elasticsearch cluster for production.
2018-12-14T08:47:07,197 WARN  [Settings] [http.enabled] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version.
2018-12-14T08:47:39,842 INFO  [OSGiRuntimeService] Nuxeo Platform Started
======================================================================
= Component Loading Status: Pending: 0 / Missing: 0 / Unstarted: 0 / Total: 492
======================================================================
2018-12-14T08:47:46,400 WARN  [JvmGcMonitorService] [gc][30] overhead, spent [801ms] collecting in the last [1s]
2018-12-14 08:47:47.996 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 105559 ms
```

**Comment by dmetzler** [comment] 2018-12-14 14:36
The already ongoing PR is for 10.3 release. I'll do a separate PR for Arm support as I don't want to jeopardize the original request with the support of a new arch.

**Comment by lag-linaro** [comment] 2018-12-14 14:53
Sounds perfectly reasonable.  Thanks @dmetzler.

**Comment by lag-linaro** [comment] 2019-02-19 11:00
Any update on this @dmetzler.  It's been a while.

**Comment by efge** [comment] 2019-02-20 14:02
@lag-linaro as the comments above state, this is working on Nuxeo 10.3 and by consequence on the latest Nuxeo LTS 2019 (10.10).

**Closed as completed by efge** 2019-02-20 14:02 UTC

**Comment by dmetzler** [comment] 2019-02-20 15:11
Added armv8 in the supported arch for 10.10

https://github.com/docker-library/official-images/pull/5457
