### ISSUE TITLE
nuxeo docker run - Failure on core-events-service.xml - Could not run configuration: Missing file: /opt/nuxeo/server/nxserver/config/mbeans (Not a directory)

### ISSUE THREAD

**Issue by jribmartins** [nuxeo/docker-nuxeo#42] opened 2020-07-21 14:34 UTC
I got following error:

```
docker run --name mynuxeo --rm -p 8096:8080 nuxeo:LTS
/docker-entrypoint.sh: ignoring /docker-entrypoint-initnuxeo.d/*
Nuxeo home:          /opt/nuxeo/server
Nuxeo configuration: /etc/nuxeo/nuxeo.conf
Include template: /opt/nuxeo/server/templates/common-base
Include template: /opt/nuxeo/server/templates/common
Include template: /opt/nuxeo/server/templates/default
Include template: /opt/nuxeo/server/templates/docker
No current configuration, generating files...
Failure on /opt/nuxeo/server/templates/common/config/mbeans/core-events-service.xml
Could not run configuration: Missing file: /opt/nuxeo/server/nxserver/config/mbeans (Not a directory)
```

I believe this is suppose to work without configuration files

**Comment by dmetzler** [comment] 2020-07-23 09:32
Here is what I get by running the same command:

```
# docker run --name mynuxeo --rm -it -p 8096:8080 nuxeo:LTS                                                                                
/docker-entrypoint.sh: ignoring /docker-entrypoint-initnuxeo.d/*
Nuxeo home:          /opt/nuxeo/server
Nuxeo configuration: /etc/nuxeo/nuxeo.conf
Include template: /opt/nuxeo/server/templates/common-base
Include template: /opt/nuxeo/server/templates/common
Include template: /opt/nuxeo/server/templates/default
Include template: /opt/nuxeo/server/templates/docker
No current configuration, generating files...
Configuration files generated.
Server started with process ID 110.
Go to http://localhost:8080/nuxeo
2020-07-23 09:28:34.044 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [1,113] milliseconds
# Running Nuxeo Preprocessor ...
Preprocessing: /opt/nuxeo/server/nxserver
Done.
# Preprocessing done.
2020-07-23T09:28:38,501 INFO  [FrameworkLoader]
======================================================================
= Starting Nuxeo Framework
======================================================================
  * Server home = /opt/nuxeo/server
  * Runtime home = /opt/nuxeo/server/nxserver
  * Data Directory = /var/lib/nuxeo/data
  * Log Directory = /var/log/nuxeo
  * Configuration Directory = /opt/nuxeo/server/nxserver/config
  * Temp Directory = /opt/nuxeo/server/tmp
======================================================================
2020-07-23T09:28:51,691 WARN  [ElasticSearchEmbeddedNode] Elasticsearch embedded configuration is ONLY for testing purpose. You need to create a dedicated Elasticsearch cluster for production.
2020-07-23T09:29:04,377 INFO  [OSGiRuntimeService] Nuxeo Platform Started
======================================================================
= Component Loading Status: Pending: 0 / Missing: 0 / Unstarted: 0 / Total: 492
======================================================================
2020-07-23 09:29:06.298 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [32,281] milliseconds
```

So I'm not able to reproduce you problem. Can you be more precise about your configuration (OS, docker version, architecture) ?

**Comment by dmetzler** [comment] 2021-01-26 12:15
Closing as no answer

**Closed as completed by dmetzler** 2021-01-26 12:15 UTC
