### ISSUE TITLE
mp-install stuck

### ISSUE THREAD

**Issue by jderusse** [nuxeo/docker-nuxeo#43] opened 2020-10-01 14:43 UTC
When runing container with packages (as describe in documentation) the command hangs on `mp-install`

https://github.com/docker-library/docs/blob/master/nuxeo/content.md#start-a-nuxeo-with-some-additional-packages

reproduct case:
```bash
$ docker run --name mynuxeo --rm -ti -p 8080:8080 -e NUXEO_PACKAGES="nuxeo-web-ui nuxeo-dam nuxeo-drive nuxeo-showcase-content nuxeo-template-rendering nuxeo-template-rendering-samples nuxeo-spreadsheet" nuxeo

/docker-entrypoint.sh: ignoring /docker-entrypoint-initnuxeo.d/*
Nuxeo home:          /opt/nuxeo/server
Nuxeo configuration: /etc/nuxeo/nuxeo.conf
Include template: /opt/nuxeo/server/templates/common-base
Include template: /opt/nuxeo/server/templates/common
Include template: /opt/nuxeo/server/templates/default
Include template: /opt/nuxeo/server/templates/docker
... <== stuck here
```	

Runing ps faux in the container:
```
$ ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
nuxeo      109  1.6  0.0   5752  3544 pts/1    Ss   14:42   0:00 bash
nuxeo      115  0.0  0.0   9392  3120 pts/1    R+   14:43   0:00  \_ ps faux
nuxeo        1  0.1  0.0   5620  3380 pts/0    Ss+  14:42   0:00 /bin/bash /docker-entrypoint.sh nuxeoctl console
nuxeo       10  0.0  0.0   5624  3676 pts/0    S+   14:42   0:00 /bin/bash /opt/nuxeo/server/bin/nuxeoctl mp-install nuxeo-web-ui nuxeo-dam nuxeo-drive nuxeo-showcase-content nuxeo-template-rendering nuxeo-templat
nuxeo       86  5.4  0.6 6950680 109448 pts/0  Sl+  14:42   0:01  \_ java -Xbootclasspath/a:/usr/local/openjdk-8/lib/tools.jar -Dlauncher.java.opts= -Dfile.encoding=UTF-8 -Dmail.mime.decodeparameters=true -Djava.u
nuxeo@615ef604f647:~$ 
```

**Comment by dmetzler** [comment] 2020-10-01 18:05
I started a brand new Cloud9 instance on AWS and launched the command that you are trying to run and I'm not able to reproduce the problem. Hence I don't think that the problem comes from the image. 

In the `ps` list, we can see that `nuxeoctl` is trying to download and install the packages from Nuxeo Connect (https://connect.nuxeo.com/), here is the expected result:

```
...
Include template: /opt/nuxeo/server/templates/docker
Optional dependencies [nuxeo-jsf-ui] will be ignored for 'nuxeo-template-rendering-6.8.3'.
Optional dependencies [nuxeo-jsf-ui] will be ignored for 'nuxeo-template-rendering-samples-6.8.3'.
Optional dependencies [nuxeo-jsf-ui] will be ignored for 'nuxeo-spreadsheet-1.4.3'.
Optional dependencies [nuxeo-jsf-ui] will be ignored for 'nuxeo-drive-1.8.5'.
Optional dependencies [nuxeo-jsf-ui] will be ignored for 'nuxeo-dam-6.4.3'.

Dependency resolution:
  Installation order (7):        nuxeo-web-ui-2.4.0/nuxeo-dam-6.4.3/nuxeo-drive-1.8.5/nuxeo-showcase-content-1.3.3/nuxeo-spreadsheet-1.4.3/nuxeo-template-rendering-6.8.3/nuxeo-template-rendering-samples-6.8.3
  Packages to download (1):      nuxeo-template-rendering-samples:6.8.3
  Local packages to install (6): nuxeo-web-ui:2.4.0, nuxeo-dam:6.4.3, nuxeo-showcase-content:1.3.3, nuxeo-spreadsheet:1.4.3, nuxeo-drive:1.8.5, nuxeo-template-rendering:6.8.3

Downloading [nuxeo-template-rendering-samples-6.8.3]...
Added nuxeo-template-rendering-samples-6.8.3
Installing nuxeo-web-ui-2.4.0
Installing nuxeo-dam-6.4.3
Installing nuxeo-drive-1.8.5
...
```

In order to troubleshoot, I would start a bash command in container and check if you can join connect:

```
$ docker run --name mynuxeo --rm -ti  nuxeo bash
nuxeo@8b0a2c8c99cf:~$ curl https://connect.nuxeo.com
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://connect.nuxeo.com/nuxeo/site/connect">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at connect.nuxeo.com Port 80</address>
</body></html>
```` 

I'm closing the ticket, as I'm not able to reproduce

**Closed as completed by dmetzler** 2020-10-01 18:05 UTC
